# ui/settings.py

from __future__ import annotations

import streamlit as st

from core.config import DEFAULTS
from core.version import __version__

STALE_THRESHOLD_DRAFT_KEY = "draft_stale_days_threshold"
SETTINGS_FEEDBACK_KEY = "settings_feedback"


def initialize_stale_threshold_draft(session_state, get_settings):
    """
    Initialize the editable value without overwriting unsaved changes.
    """
    session_state.setdeafult(
        STALE_THRESHOLD_DRAFT_KEY,
        int(get_settings("stale_days_threshold")),
    )

def apply_stale_threshold_draft(session_state):
    """
    Copy the draft threshold into the active application setting.
    """
    session_state["stale_days_threshold"] = int(
        session_state[STALE_THRESHOLD_DRAFT_KEY]
    )

def reset_settings_state(session_state):
    """Restore active settings and the stale-threshold draft."""
    for key, value in DEFAULTS.items():
        session_state[key] = value

    session_state[STALE_THRESHOLD_DRAFT_KEY] = int(
        DEFAULTS["stale_days_threshold"]
    )

def save_stale_threshold():
    """Streamlit callback for saving the stale threshold."""
    apply_stale_threshold_draft(st.session_state)
    st.session_state[SETTINGS_FEEDBACK_KEY] = (
        "Board settings saved."
    )

def reset_settings():
    """Streamlit callback for resetting all settings."""
    reset_settings_state(st.session_state)
    st.session_state[SETTINGS_FEEDBACK_KEY] = (
        "Settings reset to defaults."
    )

def render_stale_threshold_form(get_setting):
    """Render the first setting using the explicit Save workflow."""
    initialize_stale_threshold_draft(
        st.session_state,
        get_setting,
    )

    st.caption(
        "The stale-task threshold uses the new Save Settings workflow. "
        "Other settings currently apply immediately."
    )

    with st.form("stale_threshold_settings_form"):
        st.slider(
            "Stale task threshold (days)",
            min_value=1,
            max_value=30,
            step=1,
            key=STALE_THRESHOLD_DRAFT_KEY,
            help=(
                "Open tasks with no activity for this many days are treated as stale."
            ),
        )

        st.form_submit_button(
            "Save Settings",
            width="stretch",
            on_click=save_stale_threshold,
        )

def render_settings_tab(get_setting):
    st.subheader("Settings")

    feedback = st.session_state.pop(
        SETTINGS_FEEDBACK_KEY,
        None,
    )
    if feedback:
        st.success(feedback)

    st.markdown("### AI")
    st.session_state["ollama_model"] = st.text_input(
        "Ollama model",
        value=get_setting("ollama_model"),
        help="Run `ollama list` to see available models.",
    )

    st.session_state["llm_temperature"] = st.slider(
        "Temperature",
        min_value=0.0,
        max_value=1.5,
        value=float(get_setting("llm_temperature")),
        step=0.05,
        help="Lower = more consistent. Higher = more creative.",
    )

    st.session_state["llm_max_tokens"] = st.slider(
        "Max response tokens",
        min_value=128,
        max_value=2048,
        value=int(get_setting("llm_max_tokens")),
        step=16,
        help="Limits the maximum number of tokens generated by Ollama.",
    )

    st.session_state["ai_context_task_limit"] = st.slider(
        "AI context task count",
        min_value=5,
        max_value=50,
        value=int(get_setting("ai_context_task_limit")),
        step=1,
    )

    st.divider()
    st.markdown("### Board Defaults")

    st.session_state["default_statuses"] = st.selectbox(
        "Default status filter",
        options=["OPEN", "ALL"],
        index=0 if get_setting("default_statuses") == "OPEN" else 1,
    )

    queue_mode = "ALL" if get_setting("default_queues") == "ALL" else "Personal only"
    selected = st.selectbox("Default queue filter", options=["ALL", "Personal only"], index=0 if queue_mode == "ALL" else 1)
    st.session_state["default_queues"] = "ALL" if selected == "ALL" else ["Personal"]

    render_stale_threshold_form(get_setting)

    st.divider()
    st.markdown("### UI")

    st.session_state["task_note_height"] = st.slider(
        "Task note entry height",
        min_value=80,
        max_value=300,
        value=int(get_setting("task_note_height")),
        step=10,
    )

    st.session_state["note_body_height"] = st.slider(
        "Notes body height",
        min_value=120,
        max_value=600,
        value=int(get_setting("note_body_height")),
        step=10,
    )

    st.session_state["show_age_stale_columns"] = st.checkbox(
        "Show Age/Stale columns on board",
        value=bool(get_setting("show_age_stale_columns")),
    )

    st.divider()
    st.markdown("### Timezone")

    st.session_state["use_system_timezone"] = st.checkbox(
        "Use system timezone",
        value=bool(get_setting("use_system_timezone")),
    )

    st.session_state["timezone_override"] = st.text_input(
        "Manual timezone override",
        value=str(get_setting("timezone_override")),
        placeholder="America/Chicago",
        help="Leave blank to use the system timezone. Examples: America/Chicago, America/New_York",
    )

    st.divider()
    st.markdown("### Home")

    st.session_state["recent_activity_limit"] = st.slider(
        "Recent task activity items",
        min_value=3,
        max_value=20,
        value=int(get_setting("recent_activity_limit")),
        step=1
    )

    st.session_state["note_preview_length"] = st.slider(
        "Recent Activity preview length",
        min_value=20,
        max_value=250,
        value=int(get_setting("note_preview_length")),
        step=5,
    )

    st.session_state["today_focus_limit"] = st.slider(
        "Today's Focus items",
        min_value=3,
        max_value=12,
        value=int(get_setting("today_focus_limit")),
        step=1
    )
    st.session_state["recent_notes_limit"] = st.slider(
        "Recent Notes items",
        min_value=5,
        max_value=50,
        value=int(get_setting("recent_notes_limit")),
        step=5,
    )

    st.divider()
    st.markdown("### Worklog")

    st.session_state["time_log_step_minutes"] = st.slider(
        "Time log step (minutes)",
        min_value=1,
        max_value=30,
        value=int(get_setting("time_log_step_minutes")),
        step=1,
    )

    st.session_state["task_notes_limit"] = st.slider(
        "Task Notes history count",
        min_value=5,
        max_value=100,
        value=int(get_setting("task_notes_limit")),
        step=5,
    )

    st.divider()
    st.button("Reset to defaults", width="stretch", on_click=reset_settings)

    st.divider()
    st.caption(f"Boardroom Personal PSA v{__version__}")